server:
  port: 8094

spring:
  application:
    name: sonic-server-simple
    des: "Sonic云真机测试平台 - 单机版"
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: SonicQuartz
            instanceId: AUTO
          jobStore:
            isClustered: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  datasource:
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.118.76:3306/sonic?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&serverTimezone=GMT%2b8
    username: sonic
    password: RdzF2n6JD7J3Z8eT
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false

rocketmq:
  name-server: 81.70.118.76:9876
  producer:
    # 消息超过4kb则压缩
    compress-message-body-threshold: 4096
    # 消息最大为4kb
    max-message-size: 4194304
    # 生产环境请配置ACL
    # 没有特殊含义，必须配置组，否则启动报错
    group: TEST_TASK_GROUP
    # 异步发送失败重试次数
    retry-times-when-send-async-failed: 16
    # 同步发送失败重试次数
    retry-times-when-send-failed: 16
  topic:
    # 测试任务topic
    test-task-topic: TEST_TASK_TOPIC
    # 测试数据topic
    test-data-topic: TEST_DATA_TOPIC
    # 任务超时topic
    timeout-test-topic: TIMEOUT_TEST_TOPIC
  group:
    # 测试任务group
    test-task-group: TEST_TASK_GROUP
    # 测试数据group
    test-data-group: TEST_DATA_GROUP
    # 任务超时group
    timeout-test-group: TIMEOUT_TEST_GROUP

gateway:
  host: "http://localhost:8094"
  secret: sonic
  expireDay: 14

sonic:
  netty:
    port: 8095
  jobs:
    fileCron: 0 0 12 * * ?
    resultCron: 0 0 12 * * ?
    dayReportCron: 0 0 10 * * ?
    weekReportCron: 0 0 10 ? * Mon
    filesKeepDay: 60
    resultsKeepDay: 60

robot:
  client:
    host: "http://localhost:3000"
  img:
    success: "https://gitee.com/ZhouYixun/sonic-official-website/raw/master/src/assets/suc.png"
    warning: "https://gitee.com/ZhouYixun/sonic-official-website/raw/master/src/assets/warn.png"
    error: "https://gitee.com/ZhouYixun/sonic-official-website/raw/master/src/assets/fail.png"

knife4j:
  enable: true
  setting:
    enableHost: true
    enableHostText: "http://localhost:8094"
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT License | Copyright 2021 - [ZhouYiXun/sonic-server](https://github.com/ZhouYixun/sonic-server/blob/main/LICENSE)

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3
